SNT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('account/', include('account.urls')),
path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # path('__debug__/', include('debug_toolbar.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('home/', views.home,
         name='home'),
    path('detail/<int:pk>', views.note_detail, #views.NoteDetailView.as_view()
         name='note-detail'),
    path('create/', views.note_created, # views.NoteCreateView.as_view()
         name='note-create'),
    path('<int:note_id>/share', views.note_share,
         name='share_note'),
    path('like/', views.note_like,
         name='like'),
    path('testing/', views.testing, name='testing'),
    path('search/', views.note_search,
         name='note_search')
    # path('<int:note_id>/create', views.post_comment,
    #      name='note_comment')
]

notes/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class DraftedManager(models.Manager):
    def get_query_set(self):
        return super(DraftedManager, self).get_query_set(). \
            filter(status=Note.Status.DRAFT)


class PublishedManager(models.Manager):
    def get_query_set(self):
        return super(PublishedManager, self).get_query_set(). \
            filter(status=Note.Status.PUBLISHED)


class Note(models.Model):
    draft = DraftedManager()
    published = PublishedManager()

    title = models.CharField(max_length=255)
    body = models.TextField(max_length=255)
    slug = models.SlugField()
    author = models.ForeignKey(
        User,
        related_name='notes',
        on_delete=models.CASCADE
    )

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Drafted'
        PUBLISHED = 'PB', 'Published'

    status = models.CharField(
        max_length=2,
        default=Status.DRAFT,
        choices=Status.choices
    )

    publish = models.TimeField(default=timezone.now)
    created = models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='notes_liked',
                                        blank=True)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('notes:note-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['publish']
        # indexes = [
        #     models.Index(fields=['publish'])
        # ]

    objects = models.Manager()


class Comment(models.Model):
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    note = models.ForeignKey(Note, related_name='comments', on_delete=models.CASCADE)
    created = models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=True)
    body = models.TextField(max_length=255)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f"{self.author.username}_comment_on_{self.note.title}"

notes/forms.py
from .models import Note, Comment
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms
import requests

class NoteCreateForm(forms.ModelForm):

    class Meta:

        model = Note
        fields = ['title', 'body']
        widgets = {
            'url': forms.HiddenInput
        }

    def save(self, commit=True, force_insert=False):

        note = super(NoteCreateForm, self).save(commit=False)

        if commit:
            note.save()
        return note

class EmailNoteForm(forms.Form):
    name = forms.CharField(max_length=255)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']


class SearchForm(forms.Form):
    query = forms.CharField()

notes/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from .models import Note, Comment
from .forms import NoteCreateForm, EmailNoteForm, SearchForm, CommentCreateForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from actions.utils import create_action
from actions.models import Action
import requests
from django.core.paginator import Paginator
from django.contrib.postgres.search import SearchVector

# Create your views here.
def home(request):
    actions = Action.objects.all()
    following_ids = request.user.following.values_list('id', flat=True)


    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions[:5]
    notes = Note.objects.all()
    paginator = Paginator(notes, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'notes/home.html', context={
        'notes': notes,
        'actions': actions,
        'page_obj': page_obj,
        'section': 'actions'
    })

class PostListView(generic.ListView):
    model = Note
    template_name = 'notes/home.html'
    context_object_name = 'notes'
    paginate_by = 5

class NoteDetailView(generic.DetailView):
    model = Note
    context_object_name = 'note'
    extra_context = {
        'c_form': CommentCreateForm(),
    }

def note_detail(request, pk):
    note = Note.objects.get(id=pk)
    if request.method == 'POST':

        c_form = CommentCreateForm(request.POST)
        if c_form.is_valid():
            comment = c_form.save(commit=False)
            comment.note = note
            comment.author = request.user
            comment.save()
            create_action(request.user, 'commented note', comment)
            return redirect(note.get_absolute_url())

    else:
        c_form = CommentCreateForm()

        return render(request, 'notes/note_detail.html', {
            'note': note,
            'comments': note.comments.filter(active=True),
            'c_form': c_form
        })
    

class NoteCreateView(generic.CreateView):
    model = Note
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance = self.request.user
        return super(NoteCreateView, self).form_valid(form)

def note_created(request):
    if request.method == 'POST':
        form = NoteCreateForm(data=request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.author = request.user
            new_note.save()
            create_action(request.user, 'created note', new_note)
            messages.success(request, "Note added successfully")
            return redirect(new_note.get_absolute_url())#redirect(f"/notes/detail/{new_note.pk}")
    else:
        form = NoteCreateForm(data=request.GET)
        return render(
            request,
            'notes/note_form.html',
            {
                'form': form
            }
        )

def note_share(request, note_id):
    note = get_object_or_404(Note, id=note_id) # status=Note.Status.PUBLISHED
    sent = False
    if request.method == 'POST':
        form = EmailNoteForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #sending_mail
            url = request.build_absolute_uri(note.get_absolute_url())
            subject = f"{cd['name']} has shared a note with you"
            message = f"Read {note.title} at {url}\n\n" \
                      f"{cd['comments']}"
            send_mail(subject, message, 'gdenisov606@gmail.com', [cd['to']])
            sent = True
            messages.success(request, 'Mail sent successfully')
            return redirect('notes:home')
        else:
            message = messages.error(request, "Somethig went wrong")
            return render(request, 'notes/share.html', {'note': note, 'form': form, 'sent': sent})

    else:
        form = EmailNoteForm()
        return render(request, 'notes/share.html', {'note': note, 'form': form, 'sent': sent})

@require_POST
def post_comment(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    form = CommentCreateForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.note = note
        comment.save()
        # create_action(request.user, 'created note', new_note)
        messages.success(request, "Comment published")
        return redirect(note.get_absolute_url())


@require_POST
@login_required
def note_like(request):
    note_id = request.POST.get('id')
    action = request.POST.get('action')
    print(note_id, action)
    if note_id and action:
        try:
            note = Note.objects.get(id=note_id)
            if action == 'like':
                note.users_like.add(request.user)
                create_action(request.user, 'likes', note)

            else:
                note.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Note.DoesNotExist:
            pass

    return JsonResponse({'status': 'error'})

def testing(request):
    actions = Action.objects.all()
    return render(request, 'notes/testing.html', context={
        'actions': actions
    })

def note_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Note.published.annotate(
                search=SearchVector('title', 'body')
            ).filter(search=query)

    return render(request, 'notes/search.html',
                      {
                          'form': form,
                          'query': query,
                          'results': results
                      })

notes/templates/notes/base.html
{% load static %}
{% load thumbnail %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=devi   ce-width, initial-scale=1">

    <!-- Bootstrap CSS -->

    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'notes/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>SNT</title>
    {% endif %}
</head>
<body>
    <header class="site-header">

        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="#">Notes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarToggle" aria-controls="navbarToggle"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'notes:home' %}">Home</a>
                        <a class="nav-item nav-link" href="#">About</a>
                        <a class="nav-item nav-link" href="{% url 'user_list' %}">Users</a>
                    </div>
                    <!--- Navbar Right Side --->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'notes:note-create' %}">New Note</a>
                        <a class="nav-item nav-link" href="{% url 'notes:note_search' %}">Search</a>
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                         {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
                {% endif  %}
                {% block content %}{% endblock content %}
            </div>
            <div class="col-md-4">
                <div class="content-section">

                    {% if section == 'actions' %}
                    <h3>Recent actions</h3>
                    {% for action in actions %}
                    {% include 'actions/sidebar_actions.html' %}
                    {% endfor %}
                    {% else %}

                    <h3>Our Sidebar</h3>

                   <p class="text-muted">You can put any information here you'd like.</p>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a style="text-decoration:none" href="#">Latest Posts</a></li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@ ootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->

<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
<script>
    const csrftoken = Cookies.get('csrftoken');
    document.addEventListener('DOMContentLoaded', (event) => {
      // DOM loaded
      {% block domready %}
      {% endblock %}
    })
  </script>
</body>
</html>

notes/templates/notes/home.html
{% extends 'notes/base.html' %}
{% block content %}
{% for note in page_obj %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ note.author.profile.image.url }}">
    <small class="text-muted">{{ note.created|date:"d F, Y" }}</small>

    <div class="media-body">
        <div class="article-metadata">
            <a style="text-decoration:none" href="{% url 'detail_profile' note.author.profile.id %}">{{ note.author }}</a>
            <small class="text-muted">{{ note.publish }}</small>
        </div>
        <H2><a style="text-decoration:none" class="article-title" href="{% url 'notes:note-detail' note.id %}">{{note.title}}</a></H2>
        <p class="article-content">{{note.text}}</p>
    </div>
</article>


{% endfor %}

 {% if is_paginated %}
            {% if page_obj.has_previous %}
            {% with pr=page_obj.number|add:'-1'  %}
                <a class="btn btn-outline-info mb-4" href="?page=1" type="text-decoration:none">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{pr}}" type="text-decoration:none">Previous</a>
        {% endwith %}
        {% endif %}
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}" type="text-decoration:none">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}" type="text-decoration:none">{{ num }}</a>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}" type="text-decoration:none">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}" type="text-decoration:none">Last</a>


        {% endif %}
{% endblock content %}

notes/templates/notes/note_detail.html
{% extends 'notes/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


            <article class="media content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <img class="rounded-circle article-img" src="{{ note.author.profile.image.url }}">
                        <a style="decoration:none">{{ note.author}}</a>
                        {{ note.publish|date }}
                    </div>
                    {% with total_likes=note.users_like.count users_like=note.users_like.all %}
                    <h2 class="article-title">{{ note.title }}</h2>
                    <p class="article-content">{{ note.text }}</p>
                    <a data-action="{% if request.user in user_likes %}un{% endif %}like"
                       data-id="{{ note.id }}" href="#" style="text-decoration:none"
                        id="like_btn"
                    >
                        {% if request.user not in users_like %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </a>
                    <p><span id="counter">{{ total_likes }}</span> like{{ total_likes|pluralize }}</p>
                </div>
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mt-1" href="{% url 'notes:share_note' note.id %}">Forward</a>
                </div>
            </article>

    {% for comment in comments %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ comment.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a style="text-decoration:none" href="#">{{ comment.author }}</a>
            <small class="text-muted">{{ comment.created|date:"d F, Y" }}</small>
        </div>
        <p class="article-content">{{comment.body}}</p>
    </div>
</article>


{% endfor %}
<article class="media content-section">
        <form method="post">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Comment</legend>
            {{ c_form|crispy }}
          </fieldset>
            <div class="form-group">
                <button  class="btn btn-outline-info" type="submit">Comment</button>
            </div>
        </form>

    </article>
{% endwith %}
{% endblock content %}

{% block domready %}
const url = '{% url "notes:like" %}';
var options = {
method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }

  document.querySelector('#like_btn')
          .addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

    // add request body
    var formData = new FormData();
    formData.append('id', likeButton.dataset.id);
    formData.append('action', likeButton.dataset.action);
    options['body'] = formData;

    // send HTTP request
    fetch(url, options)
    .then(response => response.json())
    .then(data => {
      if (data['status'] === 'ok')
      {
        var previousAction = likeButton.dataset.action;

        // toggle button text and data-action
        var action = previousAction === 'like' ? 'unlike' : 'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;

        // update follower count
        var likeCount = document.querySelector('#counter');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
      }
    })
  });
{% endblock %}

notes/templates/notes/note_form.html
{% extends 'notes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="post">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Noting</legend>
            {{ form|crispy }}
          </fieldset>
            <div class="form-group">
                <button  class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

notes/templates/notes/search.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>notes containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for note in results %}
      <h4>
        <a style="text-decoration:none" style="decoration:none" href="{{ note.get_absolute_url }}">
          {{ note.title }}
        </a>
      </h4>
      {{ note.body|truncatewords_html:12 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a style="text-decoration:none" href='{% url "notes:note_search" %}'>Search again</a></p>
  {% else %}
    <h1>Search for notes</h1>
     <form method="get">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Noting</legend>
            {{ form|crispy }}
          </fieldset>
            <div class="form-group">
                <button  class="btn btn-outline-info" type="submit">Search</button>
            </div>
        </form>
  {% endif %}
{% endblock %}

notes/templates/notes/share.html
{% extends 'notes/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
        <form method="post">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Noting</legend>
            {{ form|crispy }}
          </fieldset>
            <div class="form-group">
                <button  class="btn btn-outline-info" type="submit">Send</button>
            </div>
        </form>
    </div>
{% endblock %}

notes/templates/notes/testing.html
{% for action in actions %}
{% load thumbnail %}

{% with user=action.user profile=action.user.profile %}
<div class="action">
  <div class="images">
    {% if profile.image %}
      {% thumbnail user.profile.photo "80x80" crop="100%" as im %}
      <a href="{{ user.profile.get_absolute_url }}">
        <img src="{{ im.url }}" alt="{{ user.profile.get_full_name }}"
         class="item-img">
      </a>
    {% endif %}
    {% if action.target %}
      {% with target=action.target %}
        {% if target.image %}
          {% thumbnail target.image "80x80" crop="100%" as im %}
          <a href="{{ target.get_absolute_url }}">
            <img src="{{ im.url }}" class="item-img">
          </a>
        {% endif %}
      {% endwith %}
    {% endif %}
  </div>
  <div class="info">
    <p>
      <span class="date">{{ action.created|timesince }} ago</span>
      <br />
      <a href="{{ user.profile.get_absolute_url }}">
        {{ user.first_name }}
      </a>
      {{ action.verb }}
      {% if action.target %}
        {% with target=action.target %}
          <a href="#">{{ target }}</a>
        {% endwith %}
      {% endif %}

    </p>
  </div>
</div>


{% endwith %}
{% endfor %}
    {{notes}}